image: node:20.9.0

stages:
  - install
  - test

install:
  stage: install
  cache:
    key:
      files:
        - yarn.lock
    paths:
      - node_modules/
    policy: pull-push
  artifacts:
    expire_in: 1h
    when: on_success
    paths:
      - node_modules/
  script:
    - yarn add jest
    - yarn install --immutable
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"

test:
  stage: test
  coverage: /All files[^|]*\|[^|]*\s+([\d\.]+)/
  cache:
    key:
      files:
        - yarn.lock
    paths:
      - node_modules/
    policy: pull
  dependencies:
    - install
  variables:
    KAFKA_BROKER_URL: $KAFKA_BROKER_URL
    KAFKA_PRODUCER_USERNAME: $KAFKA_PRODUCER_USERNAME
    KAFKA_PRODUCER_PASSWORD: $KAFKA_PRODUCER_PASSWORD
    KAFKA_REST_ENDPOINT: $KAFKA_REST_ENDPOINT
  script:
    - echo "Run unit tests for MR"
    - yarn add jest
    - yarn test
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
